export const spacingUnit = "1rem";
export const halfSpacingUnit = "0.5rem";
export const doubleSpacingUnit = "2rem";
export const maxContentWidth = "45rem";
export const fontColor = "#222";
export const backgroundColor = "#fff";
export const altBackgroundColor = "#f7f7f7"; // bg-grey-100
export const fontStack = `"fira-sans", Arial, sans-serif`;
export const fontStackHeading = `"fira-sans-2", Arial, sans-serif`;
