name: Deploy
on:
  workflow_dispatch:
  push:
    branches: [master]
permissions:
  id-token: write
  contents: read
concurrency: production
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - name: Configure AWS credentials for fetching Cognito configuration
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::858777967843:role/github-actions-ssm-read
          aws-region: us-east-1
      - name: Fetch Cognito Configuration
        run: |
          echo "COGNITO_USER_POOL_ID=$(aws ssm get-parameter --region us-east-1 --name "arn:aws:ssm:us-east-1:858777967843:parameter/mattb-sso/user-pool-id" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "COGNITO_CLIENT_ID=$(aws ssm get-parameter --region us-east-1 --name "arn:aws:ssm:us-east-1:858777967843:parameter/mattb-sso/user-pool-client-id" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
          echo "COGNITO_DOMAIN=$(aws ssm get-parameter --region us-east-1 --name "arn:aws:ssm:us-east-1:858777967843:parameter/mattb-sso/user-pool-domain" --query "Parameter.Value" --output text)" >> $GITHUB_ENV
      - run: yarn install --immutable
      - run: yarn build
      - run: yarn run check
      - name: Configure AWS credentials for deployment
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::858777967843:role/github-actions-cdk
          aws-region: us-east-1
      - run: yarn deploy
        env:
          COGNITO_USER_POOL_ID: ${{ env.COGNITO_USER_POOL_ID }}
          COGNITO_CLIENT_ID: ${{ env.COGNITO_CLIENT_ID }}
          COGNITO_DOMAIN: ${{ env.COGNITO_DOMAIN }}
  cypress-tests:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: cypress-io/github-action@v5
        with:
          project: packages/cypress-tests
      - uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/cypress-tests/cypress/screenshots
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: cypress-videos
          path: packages/cypress-tests/cypress/videos
  lighthouse:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn workspace @mattb.tech/lonesome-website-audits run lighthouse
  pa11y:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"
      - run: yarn install --immutable
      - run: yarn workspace @mattb.tech/lonesome-website-audits run pa11y
