name: Deploy
on:
  push:
    branches: [master]
permissions:
  id-token: write
  contents: read
jobs:
  check:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install --frozen-lockfile
      - run: yarn check
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::858777967843:role/LonesomeCi-GitHubActionsRole4F1BBA26-1W840M8N02102
          aws-region: us-east-1

      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: yarn deploy
  cypress-tests:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v5
        with:
          project: packages/cypress-tests
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: packages/cypress-tests/cypress/screenshots
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-videos
          path: packages/cypress-tests/cypress/videos
  lighthouse:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @mattb.tech/lonesome-website-audits run lighthouse
  pa11y:
    needs: deploy
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18"
      - run: yarn install --frozen-lockfile
      - run: yarn workspace @mattb.tech/lonesome-website-audits run pa11y
